### ISSUE TITLE
JWTconfig.ini file--where is it?

### ISSUE THREAD

**Issue by emilyanncr** [ticarpi/jwt_tool#112]
On my updated Kali Linux, I installed jwt tool and ran it a first time.

I received the following response:
No config file yet created.
Running config setup.
Configuration file built - review contents of "jwtconf.ini" to customise your options.
Make sure to set the "httplistener" value to a URL you can monitor to enable out-of-band checks.
When I ran ls no jwtconfig.ini is shown in the jwt_tool folder.  
┌──(emily㉿killa)-[/mnt/jwt_tool]
└─$ ls                                               
Dockerfile  common-headers.txt   jwt-common.txt    setup.txt
LICENSE     common-payloads.txt  jwt_tool.py
README.md   jwks-common.txt      requirements.txt
  
Does it get saved elsewhere?
Many thanks!

**Comment by emilyanncr** [comment]
Nevermind. found it

**Comment by tedmdelacruz** [comment]
for anyone else wondering. On Linux, I found it in `~/.jwt_tool`. Funny how this is not documented anywhere, they just briefly mention that a config file is generated, but not exactly where.
