### ISSUE TITLE
base64.b64decode - Could not base64-decode payload

### ISSUE THREAD

**Issue by c-sh0** [ticarpi/jwt_tool#18]
Hello, 
The JTW token i was playing with contained some URL encoding in the payload. 
Changing 
`payl = base64.b64decode(...)`
to 
`payl = base64.urlsafe_b64decode(..)`

Fixed the issue for me. :) Great tool btw.

**Comment by ticarpi** [comment]
Thanks for spotting this.
Now fixed in [commit/09fb9e5cab278ec08fd9a9b360f1d5f6e8d403d7](09fb9e5cab278ec08fd9a9b360f1d5f6e8d403d7)
