### ISSUE TITLE
RFE: support for XMLDSIG algorithms for alg header

### ISSUE THREAD

**Issue by DidierA** [ticarpi/jwt_tool#19]
I recently encountered a valid JWT (well, valid at  least for the app that used it) that could not be handled by jwt_tools because it used an invalid value in the 'alg' header; instead of HS512 it contained "http://www.w3.org/2001/04/xmldsig-more#hmac-sha512". This is apparently used for XML formatted data, and is detailed in [RFC 4051](https://www.ietf.org/rfc/rfc4051.txt).
I am not sure if this is commonly used, maybe it could be interesting to support it.
Commit of a quick and dirty implementation for my use case: https://github.com/DidierA/jwt_tool/commit/d3b1bb8eefc1368d8dd085ec5942dacb71710924

**Comment by ticarpi** [comment]
Thanks for the submission.
I've seen this before in an engagement, but I think it's pretty uncommon generally.

There are a whole load of JWT variations and 'flavours' that are in my "nice to support" list, which I will add this to.

I have no immediate plans to implement these as I'm working on new features first, but will probably be added in time.

The next version of the tool will make this sort of additional support easier anyway.
