### ISSUE TITLE
nested jwt token error

### ISSUE THREAD

**Issue by a-elk** [ticarpi/jwt_tool#24]
when i try to tamper the nested value of a jwt token i got this error :  

Traceback (most recent call last):
  File "/usr/local/bin/jwt_tool", line 1403, in <module>
    tamperToken(paylDict, headDict, sig)
  File "/usr/local/bin/jwt_tool", line 795, in tamperToken
    newVal[subclaim] = paylDict[pair][subclaim]
TypeError: 'int' object is not subscriptable

**Comment by ticarpi** [comment]
This should be fixed in [v1.3.5](https://github.com/ticarpi/jwt_tool/commit/13d61c56e9a0be11e9993a8ff9b98035b5ec54cb)
