### ISSUE TITLE
request headers

### ISSUE THREAD

**Issue by KveinAxel** [ticarpi/jwt_tool#28]
how can I use the scripts with multi headers?

**Comment by ticarpi** [comment]
Currently the tool sports only one header, however I've been testing an update that allows for multiple headers, which should be made live in the next few days.        

As a workaround I've used Burp's Find and Replace functionality in the Proxy options tabs.    

Hope that helps.

**Comment by ticarpi** [comment]
This has now been addressed in [jwt_tool v2.1.0 - (commit bbaab186afda4d45684c765526fe81407c59ee4c)](https://github.com/ticarpi/jwt_tool/commit/bbaab186afda4d45684c765526fe81407c59ee4c).  
You can supply multiple headers (only a maximum of one can contain a JWT):
`python3 jwt_tool -t http://example.com -rh "Auth: [token_here]" -rh "Another: Header"`
