### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by bryanseah234** [ticarpi/jwt_tool#30]
hi, i followed everything in the readme document

im on windows 10, have python3.8 install

i pip installed the repo and tried to run it with 

`python3 jwt_tool.py (token)`

but it just returns "access is denied".

any ideas on how to proceed? Many thanks

![image](https://user-images.githubusercontent.com/66017805/101269655-25063b00-37ac-11eb-9069-caa3fe0b8fc1.png)

**Comment by streetburner** [comment]
Chmod 777 might help you Brian

**Comment by ticarpi** [comment]
System32 is a protected directory on Windows. It's the default directory for Admin command prompt, but you don't need to be Administrator to run this tool.  

Try opening CMD.exe as the standard user, make sure you are in a directory under C:\Users\[username], then install the tool there (git clone or download as a zip and extract).
That should fix the permissions issues.
