### ISSUE TITLE
Bug on jwt_tool.py cause of "AttributeError: 'RsaKey' object has no attribute 'export_key'" exception

### ISSUE THREAD

**Issue by akabe1** [ticarpi/jwt_tool#32]
I would notify that there is a bug on the script **jwt_tool.py** _at line 704_ which cause the following exception when running a jwt scan: 

**AttributeError: 'RsaKey' object has no attribute 'export_key'**

To fix it is necessary to substitute the affected line 704 containing:
`privKey = key.export_key(format="PEM")`

with the following:
`privKey = key.exportKey(format="PEM")`

**Comment by ticarpi** [comment]
It sounds like you're using pyCrypto rather than pyCryptodome, as these have the different syntax you mention in their Crypto.PublicKey.RSA packages. 
Try the following command to install the dependencies:
`python3 -m pip install pycryptodomex`
