### ISSUE TITLE
Timestamp difference reported incorrectly?

### ISSUE THREAD

**Issue by halfluke** [ticarpi/jwt_tool#33]
On version 2.2.1 but I think i saw it on the previous version as well:

Seen timestamps:                                                                                                                                                      
[*] exp was seen <-nothing here
[*] iat is earlier than exp by: 0 days, 0 hours, 0 mins

**Comment by ticarpi** [comment]
Thanks for logging. now fixed in [v2.2.2](https://github.com/ticarpi/jwt_tool/commit/2db68d8042b730b463acb93822d769e4ab21055f)
