### ISSUE TITLE
Handle header values with Colons

### ISSUE THREAD

**Issue by rundx** [ticarpi/jwt_tool#37]
HTTP header values with colons like "Origin: https://www.example.com" gives "ValueError: too many values to unpack (expected 2)" error

https://github.com/ticarpi/jwt_tool/blob/3d92dcd69c4bf54df776aa5ec2c8c8762744a7e2/jwt_tool.py#L141

**Comment by ticarpi** [comment]
Thanks for logging. now fixed in v2.2.2](https://github.com/ticarpi/jwt_tool/commit/2db68d8042b730b463acb93822d769e4ab21055f)
