### ISSUE TITLE
cprint() miss the color arg

### ISSUE THREAD

**Issue by L3ss-dev** [ticarpi/jwt_tool#38]
error:
```
File "/mnt/hgfs/Tools/jwt_tool/jwt_tool.py", line 1238, in validateToken
    cprintc(head.decode('UTF-8'))
```
line 1238 and 1248 miss the color arg.

**Comment by ticarpi** [comment]
Now fixed in [v2.2.4](https://github.com/ticarpi/jwt_tool/commit/4045e9c6df5cf079c3ea6cd30e2c774c85a7f0e2#diff-6e193c3f7f66e4c69404766f70e92f5a759fd920eeb36ae590565ad2e719591a)
