### ISSUE TITLE
No space between curl and url

### ISSUE THREAD

**Issue by mmmds** [ticarpi/jwt_tool#44]
There is no space between the curl command and its parameter (injectUrl). Is it done purposely? In what situation would it execute properly?

https://github.com/ticarpi/jwt_tool/blob/bba0607b95181d6aff5acb418cb7d8313609f700/jwt_tool.py#L1466

```
{"typ":"JWT","alg":"HS256","kid":"|curlhttp://example.com/RCE_in_kid"}
```

**Comment by ticarpi** [comment]
Thanks so much.
Now fixed in [v2.2.4](https://github.com/ticarpi/jwt_tool/commit/4045e9c6df5cf079c3ea6cd30e2c774c85a7f0e2#diff-6e193c3f7f66e4c69404766f70e92f5a759fd920eeb36ae590565ad2e719591a)
