### ISSUE TITLE
wordlist loaded entirely into RAM

### ISSUE THREAD

**Issue by HugoPeters1024** [ticarpi/jwt_tool#6]
When using crackstation's wordlist (which is about 15GB) I went into swapping hell but luckily the python interpreter was nice and killed the process. Is there an easy way to load the wordlist in batches?

**Comment by ticarpi** [comment]
Oops, my mistake. Loaded the file in a silly way.
Now resolved in commit dd0a0d12f010f64aaa0235edcecd6bcd28b8533e by pulling dictionary file line-by-line when cracking.
Doesn't seem to affect speed.
