### ISSUE TITLE
[ERROR] ProxyError - check proxy is up and not set to tamper with requests HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /my-account (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f18fa63be80>: Failed to establish a new connection: [Errno 111] Connection refused')))     

### ISSUE THREAD

**Issue by z3dc0ps** [ticarpi/jwt_tool#73]
When I run in primary OS (Windows), no issue.
But running in VM shows this error

![image](https://user-images.githubusercontent.com/61974788/175953127-a6d46268-7b5a-4459-abbb-41673feb82af.png)

**Comment by njmulsqb** [comment]
I am also facing this issue, that too with the portswigger lab. 
I am on Kali Linux

**Comment by njmulsqb** [comment]
> I think it's because of the proxy. I was running burpsuite in my primary os and not in kali. May be that is the reason and it also shown in the error "**ProxyError**".

Do I need to run burp in background? How is that related to this tool?

**Comment by ticarpi** [comment]
`jwt_tool` is intended to be used with a proxy tool like Burp as it cannot show everything relating to the requests and responses, so findings often need to be reviewed by inspecting the HTTP traffic (e.g. in Burp). If you don't want to use a proxy tool you can specify the "no proxy" option in the tool.

**Comment by huornlmj** [comment]
Does jwt_tool assume that it will find a proxy (Burp / ZAP) on 127.0.0.1:8080 by default?
